language: java


jdk:
  - openjdk8
script: "mvn clean package -DskipTests=true -Dcheckstyle.skip=true"

branches:
  only:
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email:
    - binarywang@vip.qq.com
